### ISSUE TITLE
Skunk integration

### ISSUE THREAD

**Issue by ohuu** [epifab/yadl#23]
I saw here tpolecat/skunk#501 that you're thinking of integrating tydal with skunk. Have you got a branch you're working on? I'd like to help if I can.

**Comment by epifab** [comment]
Hi @PaperPlaneSoftware, thanks a lot for your interest! As Tydal is going through a heavy re-design for Scala 3, I thought it'd be neater to start with a fresh brand new repo: https://github.com/epifab/tydal3
At the moment I'm sort of blocked by this bug: https://github.com/lampepfl/dotty/issues/12940
I might have to re-consider some of the fundamental architecture, especially around `DbType` and `Field`, as type members are getting on the way somehow. You're more than welcome to check it out, and if you have any question feel free to drop me a message.

**Comment by ohuu** [comment]
Great! I'll pop over there and take a look 👍
